name: CI

on: pull_request

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Use node version ${{ matrix.node-version }}
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests
        run: node ./test/runTests.js

      - name: Run tests
        run: node ./test/validateModuleExportsMatchCommonJS/index.js
        if: matrix.node-version == '16.x'
